from __future__ import annotations

LEGACY_BASELINE_REVISION = "0001_initial"

# Frozen fingerprint for the operational pre-Alembic baseline. This must not
# be derived from live ORM metadata, or future model changes can silently alter
# legacy bootstrap behavior.
LEGACY_BASELINE_SPEC: dict[str, dict[str, object]] = {
    "accounts": {
        "columns": {
            "code": {"nullable": False, "primary_key": False, "type": "VARCHAR(32)"},
            "created_at": {"nullable": False, "primary_key": False, "type": "DATETIME"},
            "currency": {"nullable": False, "primary_key": False, "type": "VARCHAR(8)"},
            "id": {"nullable": False, "primary_key": True, "type": "INTEGER"},
            "is_active": {"nullable": False, "primary_key": False, "type": "BOOLEAN"},
            "kind": {"nullable": False, "primary_key": False, "type": "VARCHAR(32)"},
            "name": {"nullable": False, "primary_key": False, "type": "VARCHAR(255)"},
            "subtype": {"nullable": False, "primary_key": False, "type": "VARCHAR(64)"},
        },
        "foreign_keys": [],
        "indexes": [("kind",)],
        "unique_indexes": [("code",)],
    },
    "attachments": {
        "columns": {
            "created_at": {"nullable": False, "primary_key": False, "type": "DATETIME"},
            "description": {"nullable": True, "primary_key": False, "type": "VARCHAR(500)"},
            "id": {"nullable": False, "primary_key": True, "type": "INTEGER"},
            "path": {"nullable": False, "primary_key": False, "type": "VARCHAR(500)"},
            "sha256": {"nullable": False, "primary_key": False, "type": "VARCHAR(64)"},
        },
        "foreign_keys": [],
        "indexes": [],
        "unique_indexes": [],
    },
    "document_links": {
        "columns": {
            "document_id": {"nullable": False, "primary_key": False, "type": "INTEGER"},
            "id": {"nullable": False, "primary_key": True, "type": "INTEGER"},
            "target_id": {"nullable": False, "primary_key": False, "type": "INTEGER"},
            "target_type": {"nullable": False, "primary_key": False, "type": "VARCHAR(32)"},
        },
        "foreign_keys": [(("document_id",), "documents", ("id",))],
        "indexes": [("document_id",), ("target_id",), ("target_type",)],
        "unique_indexes": [("document_id", "target_type", "target_id")],
    },
    "documents": {
        "columns": {
            "created_at": {"nullable": False, "primary_key": False, "type": "DATETIME"},
            "created_via": {"nullable": False, "primary_key": False, "type": "VARCHAR(32)"},
            "document_type": {"nullable": False, "primary_key": False, "type": "VARCHAR(64)"},
            "id": {"nullable": False, "primary_key": True, "type": "INTEGER"},
            "notes": {"nullable": True, "primary_key": False, "type": "TEXT"},
            "original_filename": {"nullable": False, "primary_key": False, "type": "VARCHAR(255)"},
            "period_end": {"nullable": True, "primary_key": False, "type": "DATE"},
            "period_start": {"nullable": True, "primary_key": False, "type": "DATE"},
            "scope": {"nullable": False, "primary_key": False, "type": "VARCHAR(32)"},
            "sha256": {"nullable": False, "primary_key": False, "type": "VARCHAR(64)"},
            "stored_path": {"nullable": False, "primary_key": False, "type": "VARCHAR(500)"},
            "tax_year": {"nullable": False, "primary_key": False, "type": "INTEGER"},
        },
        "foreign_keys": [],
        "indexes": [("document_type",), ("scope",), ("sha256",), ("tax_year",)],
        "unique_indexes": [],
    },
    "external_event_refresh_history": {
        "columns": {
            "change_note": {"nullable": True, "primary_key": False, "type": "TEXT"},
            "external_event_id": {"nullable": False, "primary_key": False, "type": "INTEGER"},
            "id": {"nullable": False, "primary_key": True, "type": "INTEGER"},
            "payload_json": {"nullable": False, "primary_key": False, "type": "TEXT"},
            "refresh_source": {"nullable": False, "primary_key": False, "type": "VARCHAR(64)"},
            "refreshed_at": {"nullable": False, "primary_key": False, "type": "DATETIME"},
        },
        "foreign_keys": [(("external_event_id",), "external_events", ("id",))],
        "indexes": [("external_event_id",)],
        "unique_indexes": [],
    },
    "external_events": {
        "columns": {
            "event_type": {"nullable": False, "primary_key": False, "type": "VARCHAR(64)"},
            "external_id": {"nullable": False, "primary_key": False, "type": "VARCHAR(255)"},
            "id": {"nullable": False, "primary_key": True, "type": "INTEGER"},
            "import_run_id": {"nullable": True, "primary_key": False, "type": "INTEGER"},
            "journal_entry_id": {"nullable": True, "primary_key": False, "type": "INTEGER"},
            "occurred_at": {"nullable": False, "primary_key": False, "type": "DATETIME"},
            "payload_json": {"nullable": False, "primary_key": False, "type": "TEXT"},
            "provider": {"nullable": False, "primary_key": False, "type": "VARCHAR(64)"},
        },
        "foreign_keys": [
            (("import_run_id",), "imports", ("id",)),
            (("journal_entry_id",), "journal_entries", ("id",)),
        ],
        "indexes": [("provider",)],
        "unique_indexes": [("provider", "external_id")],
    },
    "imports": {
        "columns": {
            "completed_at": {"nullable": True, "primary_key": False, "type": "DATETIME"},
            "dry_run": {"nullable": False, "primary_key": False, "type": "BOOLEAN"},
            "from_date": {"nullable": True, "primary_key": False, "type": "DATE"},
            "id": {"nullable": False, "primary_key": True, "type": "INTEGER"},
            "source": {"nullable": False, "primary_key": False, "type": "VARCHAR(32)"},
            "source_path": {"nullable": True, "primary_key": False, "type": "VARCHAR(500)"},
            "started_at": {"nullable": False, "primary_key": False, "type": "DATETIME"},
            "status": {"nullable": False, "primary_key": False, "type": "VARCHAR(32)"},
            "summary_json": {"nullable": False, "primary_key": False, "type": "TEXT"},
            "to_date": {"nullable": True, "primary_key": False, "type": "DATE"},
            "warnings_json": {"nullable": False, "primary_key": False, "type": "TEXT"},
        },
        "foreign_keys": [],
        "indexes": [("source",)],
        "unique_indexes": [],
    },
    "journal_entries": {
        "columns": {
            "created_at": {"nullable": False, "primary_key": False, "type": "DATETIME"},
            "description": {"nullable": False, "primary_key": False, "type": "VARCHAR(500)"},
            "entry_date": {"nullable": False, "primary_key": False, "type": "DATE"},
            "id": {"nullable": False, "primary_key": True, "type": "INTEGER"},
            "import_run_id": {"nullable": True, "primary_key": False, "type": "INTEGER"},
            "reversal_of_entry_id": {"nullable": True, "primary_key": False, "type": "INTEGER"},
            "source_ref": {"nullable": True, "primary_key": False, "type": "VARCHAR(255)"},
            "source_type": {"nullable": False, "primary_key": False, "type": "VARCHAR(64)"},
        },
        "foreign_keys": [
            (("import_run_id",), "imports", ("id",)),
            (("reversal_of_entry_id",), "journal_entries", ("id",)),
        ],
        "indexes": [("entry_date",), ("source_type",)],
        "unique_indexes": [],
    },
    "journal_lines": {
        "columns": {
            "account_id": {"nullable": False, "primary_key": False, "type": "INTEGER"},
            "amount_cents": {"nullable": False, "primary_key": False, "type": "INTEGER"},
            "entry_id": {"nullable": False, "primary_key": False, "type": "INTEGER"},
            "id": {"nullable": False, "primary_key": True, "type": "INTEGER"},
            "memo": {"nullable": True, "primary_key": False, "type": "VARCHAR(500)"},
        },
        "foreign_keys": [(("account_id",), "accounts", ("id",)), (("entry_id",), "journal_entries", ("id",))],
        "indexes": [("account_id",), ("entry_id",)],
        "unique_indexes": [],
    },
    "period_locks": {
        "columns": {
            "action": {"nullable": False, "primary_key": False, "type": "VARCHAR(32)"},
            "created_at": {"nullable": False, "primary_key": False, "type": "DATETIME"},
            "id": {"nullable": False, "primary_key": True, "type": "INTEGER"},
            "lock_type": {"nullable": False, "primary_key": False, "type": "VARCHAR(32)"},
            "period_end": {"nullable": False, "primary_key": False, "type": "DATE"},
            "period_start": {"nullable": False, "primary_key": False, "type": "DATE"},
            "reason": {"nullable": True, "primary_key": False, "type": "TEXT"},
        },
        "foreign_keys": [],
        "indexes": [("period_end",), ("period_start",)],
        "unique_indexes": [],
    },
    "reconciliation_lines": {
        "columns": {
            "amount_cents": {"nullable": False, "primary_key": False, "type": "INTEGER"},
            "description": {"nullable": False, "primary_key": False, "type": "VARCHAR(500)"},
            "external_ref": {"nullable": True, "primary_key": False, "type": "VARCHAR(255)"},
            "id": {"nullable": False, "primary_key": True, "type": "INTEGER"},
            "session_id": {"nullable": False, "primary_key": False, "type": "INTEGER"},
            "status": {"nullable": False, "primary_key": False, "type": "VARCHAR(32)"},
            "transaction_date": {"nullable": False, "primary_key": False, "type": "DATE"},
        },
        "foreign_keys": [(("session_id",), "reconciliation_sessions", ("id",))],
        "indexes": [("session_id",)],
        "unique_indexes": [],
    },
    "reconciliation_matches": {
        "columns": {
            "applied_amount_cents": {"nullable": False, "primary_key": False, "type": "INTEGER"},
            "created_at": {"nullable": False, "primary_key": False, "type": "DATETIME"},
            "id": {"nullable": False, "primary_key": True, "type": "INTEGER"},
            "journal_line_id": {"nullable": False, "primary_key": False, "type": "INTEGER"},
            "reconciliation_line_id": {"nullable": False, "primary_key": False, "type": "INTEGER"},
            "reversal_reason": {"nullable": True, "primary_key": False, "type": "TEXT"},
            "reversed_at": {"nullable": True, "primary_key": False, "type": "DATETIME"},
        },
        "foreign_keys": [
            (("journal_line_id",), "journal_lines", ("id",)),
            (("reconciliation_line_id",), "reconciliation_lines", ("id",)),
        ],
        "indexes": [("journal_line_id",), ("reconciliation_line_id",)],
        "unique_indexes": [],
    },
    "reconciliation_session_events": {
        "columns": {
            "created_at": {"nullable": False, "primary_key": False, "type": "DATETIME"},
            "event_type": {"nullable": False, "primary_key": False, "type": "VARCHAR(32)"},
            "id": {"nullable": False, "primary_key": True, "type": "INTEGER"},
            "reason": {"nullable": True, "primary_key": False, "type": "TEXT"},
            "session_id": {"nullable": False, "primary_key": False, "type": "INTEGER"},
        },
        "foreign_keys": [(("session_id",), "reconciliation_sessions", ("id",))],
        "indexes": [("event_type",), ("session_id",)],
        "unique_indexes": [],
    },
    "reconciliation_sessions": {
        "columns": {
            "account_id": {"nullable": False, "primary_key": False, "type": "INTEGER"},
            "closed_at": {"nullable": True, "primary_key": False, "type": "DATETIME"},
            "created_at": {"nullable": False, "primary_key": False, "type": "DATETIME"},
            "id": {"nullable": False, "primary_key": True, "type": "INTEGER"},
            "statement_end": {"nullable": False, "primary_key": False, "type": "DATE"},
            "statement_ending_balance_cents": {"nullable": False, "primary_key": False, "type": "INTEGER"},
            "statement_path": {"nullable": True, "primary_key": False, "type": "VARCHAR(500)"},
            "statement_start": {"nullable": False, "primary_key": False, "type": "DATE"},
            "statement_starting_balance_cents": {"nullable": False, "primary_key": False, "type": "INTEGER"},
            "status": {"nullable": False, "primary_key": False, "type": "VARCHAR(32)"},
        },
        "foreign_keys": [(("account_id",), "accounts", ("id",))],
        "indexes": [("account_id",)],
        "unique_indexes": [],
    },
    "review_blockers": {
        "columns": {
            "blocker_date": {"nullable": False, "primary_key": False, "type": "DATE"},
            "blocker_type": {"nullable": False, "primary_key": False, "type": "VARCHAR(64)"},
            "external_event_id": {"nullable": True, "primary_key": False, "type": "INTEGER"},
            "external_id": {"nullable": False, "primary_key": False, "type": "VARCHAR(255)"},
            "id": {"nullable": False, "primary_key": True, "type": "INTEGER"},
            "opened_at": {"nullable": False, "primary_key": False, "type": "DATETIME"},
            "provider": {"nullable": False, "primary_key": False, "type": "VARCHAR(64)"},
            "resolution_entry_id": {"nullable": True, "primary_key": False, "type": "INTEGER"},
            "resolution_note": {"nullable": True, "primary_key": False, "type": "TEXT"},
            "resolution_type": {"nullable": True, "primary_key": False, "type": "VARCHAR(64)"},
            "resolved_at": {"nullable": True, "primary_key": False, "type": "DATETIME"},
            "status": {"nullable": False, "primary_key": False, "type": "VARCHAR(32)"},
        },
        "foreign_keys": [
            (("external_event_id",), "external_events", ("id",)),
            (("resolution_entry_id",), "journal_entries", ("id",)),
        ],
        "indexes": [("blocker_date",), ("blocker_type",), ("external_id",), ("provider",), ("status",)],
        "unique_indexes": [("provider", "external_id", "blocker_type")],
    },
    "settings": {
        "columns": {
            "key": {"nullable": False, "primary_key": True, "type": "VARCHAR(128)"},
            "value_json": {"nullable": False, "primary_key": False, "type": "TEXT"},
        },
        "foreign_keys": [],
        "indexes": [],
        "unique_indexes": [],
    },
    "settlement_applications": {
        "columns": {
            "application_type": {"nullable": False, "primary_key": False, "type": "VARCHAR(32)"},
            "applied_amount_cents": {"nullable": False, "primary_key": False, "type": "INTEGER"},
            "applied_date": {"nullable": False, "primary_key": False, "type": "DATE"},
            "created_at": {"nullable": False, "primary_key": False, "type": "DATETIME"},
            "id": {"nullable": False, "primary_key": True, "type": "INTEGER"},
            "reversal_reason": {"nullable": True, "primary_key": False, "type": "TEXT"},
            "reversed_at": {"nullable": True, "primary_key": False, "type": "DATETIME"},
            "settlement_line_id": {"nullable": False, "primary_key": False, "type": "INTEGER"},
            "source_line_id": {"nullable": False, "primary_key": False, "type": "INTEGER"},
        },
        "foreign_keys": [
            (("settlement_line_id",), "journal_lines", ("id",)),
            (("source_line_id",), "journal_lines", ("id",)),
        ],
        "indexes": [("applied_date",), ("settlement_line_id",), ("source_line_id",)],
        "unique_indexes": [],
    },
    "tax_obligations": {
        "columns": {
            "amount_cents": {"nullable": True, "primary_key": False, "type": "INTEGER"},
            "code": {"nullable": False, "primary_key": False, "type": "VARCHAR(128)"},
            "description": {"nullable": False, "primary_key": False, "type": "VARCHAR(500)"},
            "due_date": {"nullable": False, "primary_key": False, "type": "DATE"},
            "export_path": {"nullable": True, "primary_key": False, "type": "VARCHAR(500)"},
            "id": {"nullable": False, "primary_key": True, "type": "INTEGER"},
            "jurisdiction": {"nullable": False, "primary_key": False, "type": "VARCHAR(64)"},
            "liability_account_id": {"nullable": True, "primary_key": False, "type": "INTEGER"},
            "notes": {"nullable": True, "primary_key": False, "type": "TEXT"},
            "period_end": {"nullable": True, "primary_key": False, "type": "DATE"},
            "period_start": {"nullable": True, "primary_key": False, "type": "DATE"},
            "status": {"nullable": False, "primary_key": False, "type": "VARCHAR(32)"},
        },
        "foreign_keys": [(("liability_account_id",), "accounts", ("id",))],
        "indexes": [("due_date",), ("jurisdiction",)],
        "unique_indexes": [("code",)],
    },
}
